export interface DemoConcept {
  id: string;
  title: string;
  tag: string;
  description: string;
  problem: string;
  solution: string;
  features: string[];
  accent: string;
  icon: string;
}

export const DEMO_CONCEPTS: Record<string, DemoConcept[]> = {
  "website-development": [
    {
      id: "web-saas",
      title: "SaaS Landing Page (Sleek Dark Mode)",
      tag: "SaaS / Tech Startup",
      description: "A dark-mode high-converting landing page with 3D interactions, pricing toggles, and feature grids.",
      problem: "Tech startups struggle to show complex software benefits simply, losing signups.",
      solution: "A modern dark glassmorphic landing page with smooth scroll-driven interactive cards and simple sign-up flows.",
      features: ["Interactive pricing toggle", "3D asset loading placeholder", "Sleek feature grid", "Lead generation flow"],
      accent: "#6366f1",
      icon: "globe",
    },
    {
      id: "web-ecommerce",
      title: "Modern E-Commerce Store (Glassmorphic UI)",
      tag: "Ecommerce / Retail",
      description: "Clean product grids, cart slide-outs, micro-interactions, and secure checkout screens.",
      problem: "Local brands depend on slow marketplaces with high commission rates.",
      solution: "An independent storefront concept with beautiful product view modes, instant checkout, and order tracking.",
      features: ["Interactive product gallery", "Slide-out cart", "Razorpay integration ready", "Tactile hover effects"],
      accent: "#ec4899",
      icon: "briefcase",
    },
    {
      id: "web-local",
      title: "Local Business Hub (High Lead Gen)",
      tag: "Local Services / Shops",
      description: "Restaurant, Gym, or Clinic website with booking system, maps, and instant WhatsApp ordering.",
      problem: "Customers drop off when they can't book slots or contact the business instantly.",
      solution: "A conversion-optimized site with a clean calendar selector, Google Maps, and direct WhatsApp call triggers.",
      features: ["Dynamic slot booker", "WhatsApp ordering triggers", "Google Maps location link", "FAQ accordions"],
      accent: "#10b981",
      icon: "check",
    },
    {
      id: "web-portfolio",
      title: "Premium Creator Portfolio & Agency Site",
      tag: "Agency / Portfolios",
      description: "Sleek case studies, smooth animations, custom image grid, and a modern contact layout.",
      problem: "Traditional portfolios look static and fail to represent a creative agency's quality.",
      solution: "A premium scroll-interactive layout highlighting case studies, client reviews, and direct project inquiry form.",
      features: ["Custom project showcases", "Scroll-driven slide animations", "Fluid tag badges", "Responsive grid"],
      accent: "#f59e0b",
      icon: "palette",
    },
    {
      id: "web-realestate",
      title: "Real Estate Listings & Site Visit Booker",
      tag: "Real Estate / Property",
      description: "Property cards with photo galleries, filters by budget/location, and site-visit booking form.",
      problem: "Property dealers lose buyers who can't browse listings or schedule visits outside office hours.",
      solution: "A listings site with smart filters, gallery lightboxes, EMI calculator and instant visit booking on WhatsApp.",
      features: ["Budget & location filters", "Photo gallery lightbox", "EMI calculator widget", "Site-visit booking form"],
      accent: "#0ea5e9",
      icon: "globe",
    },
    {
      id: "web-education",
      title: "Coaching Institute & Course Website",
      tag: "Education / Coaching",
      description: "Course catalog, batch timetable, faculty profiles, results wall and admission enquiry flow.",
      problem: "Institutes depend on walk-ins because parents can't compare batches, fees and results online.",
      solution: "A trust-building education site with course pages, toppers wall, downloadable brochure and enquiry form.",
      features: ["Course & batch catalog", "Toppers/results showcase", "Faculty profile cards", "Admission enquiry flow"],
      accent: "#8b5cf6",
      icon: "file",
    },
    {
      id: "web-clinic",
      title: "Clinic & Doctor Appointment Website",
      tag: "Healthcare / Clinics",
      description: "Doctor profiles, OPD timings, service pages and token/appointment booking with reminders.",
      problem: "Clinics lose patients to busy phone lines and no visibility of OPD timings or available slots.",
      solution: "A clean medical site with doctor timings, one-tap appointment booking and automatic WhatsApp reminders.",
      features: ["Doctor profile & timings", "Appointment slot booking", "WhatsApp reminders", "Health services pages"],
      accent: "#14b8a6",
      icon: "shield",
    },
  ],
  "mobile-app-development": [
    {
      id: "app-delivery",
      title: "On-Demand Delivery & Logistics App",
      tag: "Delivery / Logistics",
      description: "Android/iOS app with live delivery tracking maps, driver details, and online payment wallet.",
      problem: "Delivery businesses lose trust when customers can't track their packages in real-time.",
      solution: "A cross-platform mobile app with live GPS map pins, status steps, and instant push updates.",
      features: ["Live map tracking panel", "Driver status updates", "Integrated wallet payment", "Push notifications"],
      accent: "#3b82f6",
      icon: "smartphone",
    },
    {
      id: "app-booking",
      title: "Local Appointment & Service App",
      tag: "Salons / Service Booking",
      description: "Beautiful services catalog, calendar slot picker, and automated booking notifications.",
      problem: "Service businesses lose bookings due to phone busy-lines and poor slot visibility.",
      solution: "A client booking app with a clean calendar grid, reminder triggers, and secure advance deposit payment.",
      features: ["Dynamic slots scheduler", "Service catalog list", "SMS/WhatsApp reminders", "Deposit payment ready"],
      accent: "#8b5cf6",
      icon: "clock",
    },
    {
      id: "app-lms",
      title: "LMS / Learning Management App",
      tag: "Education / Courses",
      description: "Video lectures player, course progress tracking, interactive quizzes, and direct chat.",
      problem: "Students drop out of web-based courses due to lack of offline access and notifications.",
      solution: "A mobile LMS app with an interactive video player, offline video saving, and direct student-teacher chat.",
      features: ["Video lecture player", "Course progress rings", "Live chat module", "Quiz submission deck"],
      accent: "#10b981",
      icon: "file",
    },
    {
      id: "app-saas",
      title: "SaaS Companion & Subscription App",
      tag: "SaaS / Utilities",
      description: "Offline-first data sync dashboard, data grids, and customizable push alert panel.",
      problem: "SaaS users need critical metrics on-the-go without opening desktop web screens.",
      solution: "A lightweight companion app with visual charts, secure offline data caching, and push alert triggers.",
      features: ["Offline data sync state", "Visual line/bar KPI charts", "Push notification controls", "Biometric login ready"],
      accent: "#ec4899",
      icon: "chart",
    },
    {
      id: "app-ecom",
      title: "E-Commerce Shopping App",
      tag: "Retail / D2C Brands",
      description: "Product catalog, wishlist, cart, UPI/Razorpay checkout and order tracking screens.",
      problem: "D2C brands lose repeat buyers without an app-first experience and push-notification offers.",
      solution: "A shopping app with fast catalog browsing, saved carts, one-tap checkout and offer push notifications.",
      features: ["Catalog & wishlist screens", "UPI/Razorpay checkout", "Order tracking timeline", "Offer push notifications"],
      accent: "#f59e0b",
      icon: "briefcase",
    },
    {
      id: "app-fitness",
      title: "Gym & Fitness Membership App",
      tag: "Fitness / Wellness",
      description: "Workout plans, membership renewal, attendance check-in and trainer chat screens.",
      problem: "Gyms track memberships on paper and members forget renewals and class timings.",
      solution: "A member app with digital check-ins, renewal reminders, plan tracking and trainer messaging.",
      features: ["Membership & renewals", "Workout plan tracker", "Class schedule alerts", "Trainer chat module"],
      accent: "#ef4444",
      icon: "clock",
    },
    {
      id: "app-community",
      title: "Community & Events App",
      tag: "Communities / Clubs",
      description: "Member directory, event RSVPs, announcements feed and group chat concepts.",
      problem: "Societies and clubs juggle WhatsApp groups where announcements and RSVPs get buried.",
      solution: "A community app with a clean announcements feed, event RSVP flow and member profiles.",
      features: ["Announcements feed", "Event RSVP flow", "Member directory", "Polls & notices"],
      accent: "#06b6d4",
      icon: "globe",
    },
  ],
  "ai-automation": [
    {
      id: "ai-support",
      title: "AI Support Agent (WhatsApp & Web)",
      tag: "Customer Support / FAQ",
      description: "AI support chatbot trained on your docs that answers FAQs 24/7 and drafts escalation tickets.",
      problem: "Support teams spend hours answering identical customer inquiries every day.",
      solution: "A custom LLM chatbot integrated into WhatsApp that answers questions instantly and qualifies leads.",
      features: ["24/7 instant AI responses", "WhatsApp Business sync", "Lead details collection", "Human escalation trigger"],
      accent: "#6366f1",
      icon: "bot",
    },
    {
      id: "ai-leads",
      title: "Sales Lead Router & WhatsApp Auto-responder",
      tag: "Sales / Lead Follow-up",
      description: "Instantly reads incoming leads from Google Sheets, sends custom WhatsApp messages, and alerts sales.",
      problem: "Sales conversions drop when lead response time is longer than 5 minutes.",
      solution: "An automated workflow that triggers the moment a form is filled, sending a personalized message instantly.",
      features: ["Google Sheets API triggers", "Personalized text templates", "Slack/Email sales alerts", "Lead tracking statuses"],
      accent: "#10b981",
      icon: "spark",
    },
    {
      id: "ai-ugc",
      title: "AI Video Creator & Social Scheduler",
      tag: "Marketing / Content Automation",
      description: "Generates video script ideas, synthesizes AI voiceovers, and schedules video files across platforms.",
      problem: "Creators struggle to post reels daily due to video editing and scripting delays.",
      solution: "A workflow that automatically generates voiceover audio, merges b-roll clips, and posts to reels.",
      features: ["Script outline generator", "AI voiceover generator sync", "Auto video compiling", "Social scheduling triggers"],
      accent: "#f59e0b",
      icon: "video",
    },
    {
      id: "ai-invoice",
      title: "E-invoice & PDF OCR Line Extractor",
      tag: "Finance / Operations",
      description: "Scans email PDF receipts, extracts pricing line items via OCR, and uploads directly to QuickBooks.",
      problem: "Accounting teams waste days typing line items from invoice PDFs manually.",
      solution: "An automated pipeline that reads PDFs via OCR, validates amounts, and syncs to accounting tools.",
      features: ["PDF document reader OCR", "Calculations double-checker", "Direct QuickBooks API sync", "Error logging alerts"],
      accent: "#3b82f6",
      icon: "file",
    },
    {
      id: "ai-hr",
      title: "Resume Screening & Shortlist Bot",
      tag: "HR / Recruitment",
      description: "Reads incoming resumes, scores them against the job description and emails a ranked shortlist.",
      problem: "HR teams spend days manually screening hundreds of irrelevant applications.",
      solution: "An AI pipeline that parses resumes, scores fit against criteria and delivers a ranked sheet daily.",
      features: ["Resume parsing & scoring", "JD match ranking", "Daily shortlist email", "Google Sheets sync"],
      accent: "#ec4899",
      icon: "file",
    },
    {
      id: "ai-reports",
      title: "Auto Report Generator (Excel → PDF → Email)",
      tag: "Operations / MIS",
      description: "Pulls raw Excel/Sheet data, builds a clean PDF report and emails it on schedule.",
      problem: "Managers waste every Monday compiling the same weekly numbers into reports.",
      solution: "A scheduled workflow that formats data into branded PDF reports and emails stakeholders automatically.",
      features: ["Scheduled data pulls", "Branded PDF templates", "Auto email delivery", "Error alerts"],
      accent: "#8b5cf6",
      icon: "chart",
    },
    {
      id: "ai-bookingbot",
      title: "WhatsApp Booking Assistant",
      tag: "Bookings / Front Desk",
      description: "AI assistant on WhatsApp that checks slots, books appointments and sends reminders.",
      problem: "Front desks miss bookings after hours and double-book busy slots.",
      solution: "A WhatsApp bot that reads your calendar, offers free slots, confirms bookings and reminds clients.",
      features: ["Calendar slot lookup", "Instant booking confirmations", "Automatic reminders", "Reschedule handling"],
      accent: "#14b8a6",
      icon: "bot",
    },
  ],
  "logo-branding": [
    {
      id: "brand-minimal",
      title: "Minimalist Tech Brand Identity",
      tag: "Tech / Modern Startups",
      description: "Clean modern typography vectors, futuristic logo icon, and dark/light mode palette assets.",
      problem: "New startups look amateur without a structured, modern, vector-perfect brand system.",
      solution: "A high-end minimal identity bundle including dynamic font pairings, colors, and responsive vector SVGs.",
      features: ["Responsive vector SVG paths", "Font pairing stylesheet", "Light/Dark background guides", "Brand booklet template"],
      accent: "#6366f1",
      icon: "palette",
    },
    {
      id: "brand-retail",
      title: "Premium Lifestyle & Retail Identity",
      tag: "Lifestyle / E-Commerce",
      description: "Warm organic colors, elegant typography wordmark, and premium packaging label templates.",
      problem: "Product brands fail to justify premium pricing due to basic, generic logo designs.",
      solution: "An organic luxury branding system with elegant typography, custom packaging vectors, and brand guide.",
      features: ["Packaging label guidelines", "Warm editorial font sheets", "Custom vectors assets", "Social media templates"],
      accent: "#ec4899",
      icon: "briefcase",
    },
    {
      id: "brand-creator",
      title: "Bold Creator & Media Brand Kit",
      tag: "Media / Content Creators",
      description: "High-contrast geometric shapes, neon accent templates, and social media header banners.",
      problem: "Social media creators struggle to stay recognizable across different media channels.",
      solution: "A bold, cohesive brand kit with high-contrast layouts, custom stream templates, and avatar mockups.",
      features: ["Cohesive avatars templates", "High-contrast geometric styles", "Dynamic stream overlay assets", "Social banner templates"],
      accent: "#f59e0b",
      icon: "spark",
    },
    {
      id: "brand-corporate",
      title: "Corporate Trust Identity Bundle",
      tag: "Consulting / Finance",
      description: "Professional slate-blue colors, balanced symmetrical wordmark, and letterhead guides.",
      problem: "Financial/legal firms struggle to project corporate authority with modern amateur logos.",
      solution: "A symmetrical branding system prioritizing legibility, vector precision, and professional stationary guides.",
      features: ["Print-ready letterhead formats", "Corporate color guides", "Balanced symmetrical icon", "Presentation slide decks"],
      accent: "#3b82f6",
      icon: "shield",
    },
    {
      id: "brand-restaurant",
      title: "Restaurant & Café Identity Kit",
      tag: "Food / Hospitality",
      description: "Appetizing logo mark, menu design system, signage mockups and social post templates.",
      problem: "Eateries with great food look forgettable next to branded chains.",
      solution: "A warm food-brand identity with menu layouts, packaging stickers and Instagram-ready templates.",
      features: ["Menu design system", "Packaging & sticker set", "Signage mockups", "Instagram templates"],
      accent: "#ef4444",
      icon: "palette",
    },
    {
      id: "brand-fashion",
      title: "Fashion & Boutique Label Identity",
      tag: "Fashion / Apparel",
      description: "Elegant wordmark, hang-tag and label designs, lookbook layout and story highlight icons.",
      problem: "Boutique labels struggle to look premium against big fashion brands online.",
      solution: "A refined fashion identity with tag/label designs, lookbook grids and cohesive social styling.",
      features: ["Hang-tag & label designs", "Lookbook grid layout", "Highlight icon set", "Brand color story"],
      accent: "#a855f7",
      icon: "spark",
    },
    {
      id: "brand-refresh",
      title: "Modern Rebrand Refresh Kit",
      tag: "Rebranding / Upgrade",
      description: "Refreshes an outdated logo into a modern mark while keeping brand recognition intact.",
      problem: "Older businesses fear losing recognition but their dated logo drives younger customers away.",
      solution: "A careful rebrand that modernizes the mark, cleans the palette and ships old-vs-new usage guides.",
      features: ["Logo modernization", "Before/after guide", "Updated color palette", "Rollout checklist"],
      accent: "#10b981",
      icon: "check",
    },
  ],
  "video-editing": [
    {
      id: "vid-viral",
      title: "Viral Tiktok & Instagram Reels Editing Flow",
      tag: "Social Media / TikTok",
      description: "High-energy zoom cuts, sound effects, colored kinetic text subtitles, and upbeat pacing.",
      problem: "Reels get scrolled past instantly without engaging hooks and fast-paced edits.",
      solution: "A viral editing system with synchronized sound effects, visual zoom callouts, and colored dynamic captions.",
      features: ["Kinetic text subtitle sync", "Visual zoom hooks", "Engagement sound design", "Fast pacing cuts"],
      accent: "#ec4899",
      icon: "video",
    },
    {
      id: "vid-doc",
      title: "Premium YouTube Documentary & Storytelling Style",
      tag: "YouTube / Documentary",
      description: "Smooth slide transitions, cinematic color grading, slow-motion overlays, and deep voiceover sync.",
      problem: "Long-form videos suffer from low watch-time without pacing variety and clean b-rolls.",
      solution: "A documentary-style edit featuring color grading, smooth slide overlays, and balanced sound mixing.",
      features: ["Cinematic color mapping", "Clean slide b-roll sync", "Deep sound/music mixing", "Long-form pacing structures"],
      accent: "#3b82f6",
      icon: "globe",
    },
    {
      id: "vid-ad",
      title: "Scroll-Stopping Facebook/Instagram Video Ads",
      tag: "E-Commerce Ads / UGC",
      description: "15-second product promo clips with bold text callouts, split-screen modes, and strong CTAs.",
      problem: "Ad budgets are wasted on generic videos that fail to explain product value in 3 seconds.",
      solution: "High-impact social ad videos prioritizing hook variations, split screens, and animated benefit callouts.",
      features: ["3-second hook variations", "Split-screen product showcase", "Bold value callout text", "Actionable call-to-actions"],
      accent: "#10b981",
      icon: "megaphone",
    },
    {
      id: "vid-explain",
      title: "Explainer Video & Vector Motion Graphics",
      tag: "SaaS / Product Explainer",
      description: "Animated flat vector shapes, product dashboard screen captures, and synced narration.",
      problem: "SaaS products struggle to onboard new users without visual step-by-step guides.",
      solution: "An animated explainer video using animated dashboard layouts and clear voiceover guidance.",
      features: ["Dashboard capture guides", "Animated flat vector shapes", "Synced narration tracks", "Onboarding step highlights"],
      accent: "#8b5cf6",
      icon: "file",
    },
    {
      id: "vid-wedding",
      title: "Cinematic Wedding & Event Highlights",
      tag: "Weddings / Events",
      description: "Emotional highlight reels with music sync, color grading and teaser cuts for social sharing.",
      problem: "Hours of raw event footage sit unused because families never get a shareable cut.",
      solution: "A cinematic highlight edit with story pacing, graded tones and 60-second teasers for Instagram.",
      features: ["Music-synced highlights", "Cinematic color grade", "60-sec teaser cut", "Full ceremony chapters"],
      accent: "#f59e0b",
      icon: "video",
    },
    {
      id: "vid-corporate",
      title: "Corporate Profile & Interview Videos",
      tag: "Corporate / B2B",
      description: "Polished company profile edits with lower-thirds, b-roll inserts and clean interview cuts.",
      problem: "B2B companies lose credibility with shaky, unedited founder and factory footage.",
      solution: "A professional corporate edit with branded lower-thirds, smooth b-roll and tight interview pacing.",
      features: ["Branded lower-thirds", "Interview cleanup cuts", "B-roll sequencing", "Logo outro animation"],
      accent: "#6366f1",
      icon: "briefcase",
    },
    {
      id: "vid-shorts",
      title: "Long Video → Shorts Repurposing System",
      tag: "YouTube / Podcast Clips",
      description: "Turns podcasts and long videos into vertical clips with captions and hook-first editing.",
      problem: "Creators sit on hours of long content that never reaches short-form audiences.",
      solution: "A repurposing pipeline that finds strong moments and ships caption-ready vertical clips weekly.",
      features: ["Hook-first clip selection", "Auto caption styling", "Vertical reframing", "Weekly clip batches"],
      accent: "#ef4444",
      icon: "spark",
    },
  ],
  "digital-marketing": [
    {
      id: "mkt-maps",
      title: "Local Google Maps SEO Optimizer",
      tag: "Local SEO / GBP Boost",
      description: "Google Business Profile optimization, keyword citation building, and automatic review reminders.",
      problem: "Local shops lose nearby organic customers to competitors ranking higher on Google Maps.",
      solution: "A Maps SEO package to align keywords, build citations, and automate customer reviews generation.",
      features: ["Google Maps profile audits", "Local citation submissions", "Reviews reminder automation", "Location map embed code"],
      accent: "#3b82f6",
      icon: "globe",
    },
    {
      id: "mkt-ads",
      title: "High-ROAS Facebook & Meta Ads Campaign",
      tag: "Paid Advertising / Leads",
      description: "Custom audience research, split-test copies, pixel tracking, and lead-gen landing page setup.",
      problem: "E-commerce brands waste money on broad Meta ads without proper custom audience splits.",
      solution: "A results-oriented campaign setup featuring creative testing, custom exclusions, and pixel conversions.",
      features: ["Meta Pixel tracking setup", "Audience research blueprints", "Copy variations split tests", "Lead funnel design"],
      accent: "#ec4899",
      icon: "megaphone",
    },
    {
      id: "mkt-seo",
      title: "On-Page SEO & Content Marketing Blueprint",
      tag: "Organic Growth / SEO",
      description: "Full site technical audit, page speed enhancements, and keyword content outlines.",
      problem: "Websites receive zero organic search traffic due to slow load times and unoptimized keywords.",
      solution: "On-page content blueprint mapping key search terms, headings layout, and page speed adjustments.",
      features: ["Keyword maps sheets", "Technical SEO audits", "Speed performance edits", "Blog outline planners"],
      accent: "#10b981",
      icon: "chart",
    },
    {
      id: "mkt-funnel",
      title: "Automated WhatsApp & Email Marketing Funnel",
      tag: "Automation / Retention",
      description: "Automated sequence flows for abandoned carts, broadcast triggers, and lead capture boxes.",
      problem: "Online stores lose 70% of potential buyers who abandon carts and never receive follow-ups.",
      solution: "Automated follow-up drip campaigns on WhatsApp and Email reminding users to complete checkout.",
      features: ["Abandoned cart triggers", "Drip sequencers configurations", "Lead capture forms", "Discount coupon trigger"],
      accent: "#f59e0b",
      icon: "spark",
    },
    {
      id: "mkt-social",
      title: "Social Media Management & Content Calendar",
      tag: "Social Media / Branding",
      description: "Monthly content calendar, branded post templates, caption bank and posting schedule.",
      problem: "Business pages go silent for weeks because there's no plan for what to post.",
      solution: "A managed content system with a monthly calendar, ready templates and consistent posting cadence.",
      features: ["Monthly content calendar", "Branded post templates", "Caption & hashtag bank", "Posting schedule"],
      accent: "#8b5cf6",
      icon: "palette",
    },
    {
      id: "mkt-google",
      title: "Google Search Ads Lead Machine",
      tag: "Google Ads / Local Leads",
      description: "High-intent keyword campaigns, negative keyword lists, call tracking and lead form landing page.",
      problem: "Service businesses burn ad budget on broad keywords that bring calls from the wrong city.",
      solution: "Tightly targeted search campaigns with location filters, call extensions and conversion tracking.",
      features: ["High-intent keyword sets", "Negative keyword lists", "Call & form tracking", "Location targeting"],
      accent: "#f59e0b",
      icon: "megaphone",
    },
    {
      id: "mkt-ugc",
      title: "Influencer & UGC Campaign Kit",
      tag: "Influencers / UGC",
      description: "Creator brief templates, product seeding plan, UGC usage checklist and performance tracker.",
      problem: "Brands pay influencers without briefs or rights and get unusable one-off posts.",
      solution: "A structured campaign kit with creator briefs, usage-rights checklist and a results tracking sheet.",
      features: ["Creator brief templates", "Usage-rights checklist", "Seeding & outreach plan", "Performance tracker"],
      accent: "#06b6d4",
      icon: "video",
    },
  ],
  "data-dashboard": [
    {
      id: "dash-sales",
      title: "Sales Performance Dashboard (Power BI)",
      tag: "Sales / Revenue",
      description: "Revenue trends, top products, team leaderboards and target-vs-actual gauges in one view.",
      problem: "Owners find out about a bad month only after it ends, buried in Excel sheets.",
      solution: "A live sales dashboard with daily trends, product rankings and target tracking at a glance.",
      features: ["Revenue trend lines", "Target vs actual gauges", "Top product rankings", "Team leaderboard"],
      accent: "#3b82f6",
      icon: "chart",
    },
    {
      id: "dash-finance",
      title: "Finance & Cashflow Tracker",
      tag: "Finance / Accounts",
      description: "Cash-in vs cash-out, expense categories, receivables aging and monthly P&L snapshot.",
      problem: "Businesses feel profitable but run out of cash because receivables are invisible.",
      solution: "A finance board showing cashflow, pending payments aging and expense breakdowns clearly.",
      features: ["Cashflow waterfall", "Receivables aging", "Expense categories", "Monthly P&L snapshot"],
      accent: "#10b981",
      icon: "file",
    },
    {
      id: "dash-inventory",
      title: "Inventory & Stock Alerts Board",
      tag: "Inventory / Warehouse",
      description: "Stock levels by item, reorder alerts, fast/slow movers and supplier lead-time view.",
      problem: "Stockouts of best-sellers and piles of dead stock eat margins silently.",
      solution: "An inventory dashboard with reorder alerts, movement analysis and supplier tracking.",
      features: ["Low-stock alerts", "Fast/slow mover analysis", "Reorder point tracking", "Supplier lead times"],
      accent: "#f59e0b",
      icon: "briefcase",
    },
    {
      id: "dash-marketing",
      title: "Marketing ROI Dashboard",
      tag: "Marketing / Ads",
      description: "Ad spend vs leads vs sales across Meta/Google, cost-per-lead trends and channel comparison.",
      problem: "Marketing budgets get renewed without knowing which channel actually brings paying customers.",
      solution: "A cross-channel ROI board connecting spend to leads to revenue with per-channel CPL.",
      features: ["Cross-channel spend view", "Cost-per-lead trends", "Lead→sale funnel", "Campaign comparison"],
      accent: "#ec4899",
      icon: "megaphone",
    },
    {
      id: "dash-hr",
      title: "HR & Attendance Analytics",
      tag: "HR / Teams",
      description: "Attendance heatmaps, leave balances, overtime trends and headcount by department.",
      problem: "HR compiles attendance manually every month and misses overtime cost spikes.",
      solution: "An HR board with attendance patterns, leave tracking and overtime cost visibility.",
      features: ["Attendance heatmap", "Leave balance tracker", "Overtime cost trends", "Department headcount"],
      accent: "#8b5cf6",
      icon: "clock",
    },
    {
      id: "dash-excel",
      title: "Excel Cleanup & Automated MIS Reports",
      tag: "Excel / MIS",
      description: "Messy multi-sheet Excel turned into clean auto-refreshing MIS with pivot summaries.",
      problem: "Daily MIS takes hours of copy-paste and still ships with formula errors.",
      solution: "Restructured workbooks with automated pivots, validations and one-click refresh reporting.",
      features: ["Data cleanup & structure", "Auto-refresh pivots", "Validation rules", "One-click MIS report"],
      accent: "#14b8a6",
      icon: "file",
    },
    {
      id: "dash-exec",
      title: "Executive KPI Command Center",
      tag: "Founders / Management",
      description: "One screen for the numbers that matter: revenue, cash, pipeline, ops health and alerts.",
      problem: "Founders juggle five tools to answer one question: how is the business doing today?",
      solution: "A single command-center dashboard combining key metrics from all departments with alerts.",
      features: ["Cross-department KPIs", "Threshold alerts", "Drill-down views", "Mobile-friendly layout"],
      accent: "#6366f1",
      icon: "shield",
    },
  ],
  "resume-career": [
    {
      id: "cv-ats",
      title: "ATS-Optimized Corporate Resume",
      tag: "Corporate / MNC Jobs",
      description: "Keyword-matched, cleanly structured resume that passes applicant tracking systems.",
      problem: "Strong candidates get auto-rejected because their resume format confuses ATS software.",
      solution: "An ATS-safe rewrite with role keywords, quantified achievements and a clean single-column layout.",
      features: ["ATS-safe formatting", "JD keyword matching", "Quantified achievements", "Editable + PDF files"],
      accent: "#3b82f6",
      icon: "file",
    },
    {
      id: "cv-fresher",
      title: "Fresher / Campus Placement Resume",
      tag: "Freshers / Internships",
      description: "Projects-first resume for freshers highlighting skills, internships and academics smartly.",
      problem: "Freshers with no experience send empty-looking resumes that get ignored.",
      solution: "A projects-and-skills-first layout that makes coursework and internships look professional.",
      features: ["Projects-first structure", "Skills matrix section", "Internship highlights", "Clean one-pager"],
      accent: "#10b981",
      icon: "spark",
    },
    {
      id: "cv-tech",
      title: "Tech & IT Professional Resume",
      tag: "Developers / IT",
      description: "Stack-focused resume with impact bullets, GitHub/portfolio links and system keywords.",
      problem: "Tech recruiters skim for stack and impact; buzzword-stuffed resumes hide both.",
      solution: "A developer resume with clear stack sections, measurable impact bullets and project links.",
      features: ["Tech stack sections", "Impact-based bullets", "GitHub/portfolio links", "Role-specific keywords"],
      accent: "#6366f1",
      icon: "code",
    },
    {
      id: "cv-executive",
      title: "Senior Executive Profile Pack",
      tag: "Managers / Leadership",
      description: "Leadership-focused two-pager with career highlights, P&L ownership and board-ready summary.",
      problem: "Senior profiles read like task lists instead of leadership and business impact stories.",
      solution: "An executive resume emphasizing outcomes, team scale, budgets owned and strategic wins.",
      features: ["Leadership summary", "P&L and team scale", "Career highlight reel", "Two-page structure"],
      accent: "#475569",
      icon: "briefcase",
    },
    {
      id: "cv-linkedin",
      title: "LinkedIn Profile Makeover",
      tag: "LinkedIn / Personal Brand",
      description: "Headline, about section, experience rewrite and keyword tuning for recruiter search.",
      problem: "Recruiters search LinkedIn first; weak headlines keep good profiles invisible.",
      solution: "A full profile rewrite with searchable keywords, a compelling about story and clean sections.",
      features: ["Search-keyword tuning", "Headline & about rewrite", "Experience restructure", "Banner suggestion"],
      accent: "#0ea5e9",
      icon: "globe",
    },
    {
      id: "cv-coverletter",
      title: "Cover Letter & Application Kit",
      tag: "Applications / Follow-ups",
      description: "Tailored cover letter template, email scripts and follow-up message pack.",
      problem: "Generic 'Dear Sir' cover letters get applications deleted in seconds.",
      solution: "A personalized cover letter plus ready email and follow-up scripts tuned to the target role.",
      features: ["Tailored cover letter", "Application email script", "Follow-up templates", "Editable formats"],
      accent: "#f59e0b",
      icon: "check",
    },
    {
      id: "cv-portfolio",
      title: "Personal Portfolio Mini-Site",
      tag: "Portfolio / Personal Site",
      description: "One-page personal site with resume download, project showcase and contact form.",
      problem: "A resume attachment can't show personality, projects or design sense.",
      solution: "A sleek one-page portfolio with project cards, testimonials and a resume download button.",
      features: ["One-page personal site", "Project showcase cards", "Resume download", "Contact form"],
      accent: "#ec4899",
      icon: "palette",
    },
  ],
  "custom-software": [
    {
      id: "soft-crm",
      title: "Custom CRM & Lead Manager",
      tag: "Sales / CRM",
      description: "Lead pipeline stages, follow-up reminders, notes history and team assignment views.",
      problem: "Leads scattered across WhatsApp, Excel and diaries silently go cold.",
      solution: "A simple CRM with pipeline boards, reminder nudges and complete client history in one place.",
      features: ["Pipeline stage board", "Follow-up reminders", "Client notes history", "Team assignments"],
      accent: "#3b82f6",
      icon: "briefcase",
    },
    {
      id: "soft-billing",
      title: "Billing & Invoice System (GST-ready)",
      tag: "Billing / Accounts",
      description: "GST invoices, payment status tracking, customer ledger and PDF/WhatsApp sharing.",
      problem: "Manual billing causes GST errors and nobody knows who still owes money.",
      solution: "A billing system with GST-compliant invoices, ledgers and one-tap invoice sharing.",
      features: ["GST invoice formats", "Payment status ledger", "PDF/WhatsApp sharing", "Customer statements"],
      accent: "#10b981",
      icon: "file",
    },
    {
      id: "soft-inventory",
      title: "Inventory & Order Management System",
      tag: "Stock / Orders",
      description: "Stock in/out entries, low-stock alerts, order processing and barcode-ready item master.",
      problem: "Growing shops outgrow Excel — double entries and missing stock become routine.",
      solution: "A stock system with clean item masters, movement logs, alerts and order workflows.",
      features: ["Stock movement logs", "Low-stock alerts", "Order processing flow", "Barcode-ready items"],
      accent: "#f59e0b",
      icon: "chart",
    },
    {
      id: "soft-booking",
      title: "Multi-Branch Booking Engine",
      tag: "Bookings / Scheduling",
      description: "Centralized slot management across branches with staff calendars and payment holds.",
      problem: "Multi-branch businesses double-book because each branch runs its own register.",
      solution: "One booking engine with branch calendars, staff availability and advance payment holds.",
      features: ["Branch-wise calendars", "Staff availability rules", "Advance payment holds", "Central admin view"],
      accent: "#ec4899",
      icon: "clock",
    },
    {
      id: "soft-erp",
      title: "Mini ERP for Small Factories",
      tag: "Manufacturing / Ops",
      description: "Orders → production → dispatch tracking with material usage and simple costing.",
      problem: "Small factories track production on whiteboards and lose track of material costs.",
      solution: "A lightweight ERP covering order intake, production stages, dispatch and cost visibility.",
      features: ["Order→dispatch tracking", "Production stage board", "Material usage logs", "Simple job costing"],
      accent: "#6366f1",
      icon: "shield",
    },
    {
      id: "soft-portal",
      title: "Client / Student Portal with Login",
      tag: "Portals / Members",
      description: "Secure login portal for clients or students with documents, status and messaging.",
      problem: "Teams answer the same 'what's the status?' question on calls all day.",
      solution: "A self-service portal where members log in to see status, files and updates anytime.",
      features: ["Secure member login", "Status & documents area", "Announcements feed", "Message threads"],
      accent: "#14b8a6",
      icon: "globe",
    },
    {
      id: "soft-api",
      title: "API Integration & Middleware Bridge",
      tag: "Integrations / Sync",
      description: "Connects your existing tools — CRM↔WhatsApp↔Sheets↔Payment gateway — into one flow.",
      problem: "Teams re-type the same data into three tools because none of them talk to each other.",
      solution: "A middleware bridge that syncs data between your existing tools automatically and logs errors.",
      features: ["Two-way data sync", "Webhook automations", "Error logging & retries", "No tool replacement needed"],
      accent: "#8b5cf6",
      icon: "code",
    },
  ],
};
