export interface DemoConcept {
  id: string;
  title: string;
  tag: string;
  description: string;
  problem: string;
  solution: string;
  features: string[];
  accent: string;
  icon: string;
}

export const DEMO_CONCEPTS: Record<string, DemoConcept[]> = {
  "website-development": [
    {
      id: "web-saas",
      title: "SaaS Landing Page (Sleek Dark Mode)",
      tag: "SaaS / Tech Startup",
      description: "A dark-mode high-converting landing page with 3D interactions, pricing toggles, and feature grids.",
      problem: "Tech startups struggle to show complex software benefits simply, losing signups.",
      solution: "A modern dark glassmorphic landing page with smooth scroll-driven interactive cards and simple sign-up flows.",
      features: ["Interactive pricing toggle", "3D asset loading placeholder", "Sleek feature grid", "Lead generation flow"],
      accent: "#6366f1",
      icon: "globe",
    },
    {
      id: "web-ecommerce",
      title: "Modern E-Commerce Store (Glassmorphic UI)",
      tag: "Ecommerce / Retail",
      description: "Clean product grids, cart slide-outs, micro-interactions, and secure checkout screens.",
      problem: "Local brands depend on slow marketplaces with high commission rates.",
      solution: "An independent storefront concept with beautiful product view modes, instant checkout, and order tracking.",
      features: ["Interactive product gallery", "Slide-out cart", "Razorpay integration ready", "Tactile hover effects"],
      accent: "#ec4899",
      icon: "briefcase",
    },
    {
      id: "web-local",
      title: "Local Business Hub (High Lead Gen)",
      tag: "Local Services / Shops",
      description: "Restaurant, Gym, or Clinic website with booking system, maps, and instant WhatsApp ordering.",
      problem: "Customers drop off when they can't book slots or contact the business instantly.",
      solution: "A conversion-optimized site with a clean calendar selector, Google Maps, and direct WhatsApp call triggers.",
      features: ["Dynamic slot booker", "WhatsApp ordering triggers", "Google Maps location link", "FAQ accordions"],
      accent: "#10b981",
      icon: "check",
    },
    {
      id: "web-portfolio",
      title: "Premium Creator Portfolio & Agency Site",
      tag: "Agency / Portfolios",
      description: "Sleek case studies, smooth animations, custom image grid, and a modern contact layout.",
      problem: "Traditional portfolios look static and fail to represent a creative agency's quality.",
      solution: "A premium scroll-interactive layout highlighting case studies, client reviews, and direct project inquiry form.",
      features: ["Custom project showcases", "Scroll-driven slide animations", "Fluid tag badges", "Responsive grid"],
      accent: "#f59e0b",
      icon: "palette",
    },
  ],
  "mobile-app-development": [
    {
      id: "app-delivery",
      title: "On-Demand Delivery & Logistics App",
      tag: "Delivery / Logistics",
      description: "Android/iOS app with live delivery tracking maps, driver details, and online payment wallet.",
      problem: "Delivery businesses lose trust when customers can't track their packages in real-time.",
      solution: "A cross-platform mobile app with live GPS map pins, status steps, and instant push updates.",
      features: ["Live map tracking panel", "Driver status updates", "Integrated wallet payment", "Push notifications"],
      accent: "#3b82f6",
      icon: "smartphone",
    },
    {
      id: "app-booking",
      title: "Local Appointment & Service App",
      tag: "Salons / Service Booking",
      description: "Beautiful services catalog, calendar slot picker, and automated booking notifications.",
      problem: "Service businesses lose bookings due to phone busy-lines and poor slot visibility.",
      solution: "A client booking app with a clean calendar grid, reminder triggers, and secure advance deposit payment.",
      features: ["Dynamic slots scheduler", "Service catalog list", "SMS/WhatsApp reminders", "Deposit payment ready"],
      accent: "#8b5cf6",
      icon: "clock",
    },
    {
      id: "app-lms",
      title: "LMS / Learning Management App",
      tag: "Education / Courses",
      description: "Video lectures player, course progress tracking, interactive quizzes, and direct chat.",
      problem: "Students drop out of web-based courses due to lack of offline access and notifications.",
      solution: "A mobile LMS app with an interactive video player, offline video saving, and direct student-teacher chat.",
      features: ["Video lecture player", "Course progress rings", "Live chat module", "Quiz submission deck"],
      accent: "#10b981",
      icon: "file",
    },
    {
      id: "app-saas",
      title: "SaaS Companion & Subscription App",
      tag: "SaaS / Utilities",
      description: "Offline-first data sync dashboard, data grids, and customizable push alert panel.",
      problem: "SaaS users need critical metrics on-the-go without opening desktop web screens.",
      solution: "A lightweight companion app with visual charts, secure offline data caching, and push alert triggers.",
      features: ["Offline data sync state", "Visual line/bar KPI charts", "Push notification controls", "Biometric login ready"],
      accent: "#ec4899",
      icon: "chart",
    },
  ],
  "ai-automation": [
    {
      id: "ai-support",
      title: "AI Support Agent (WhatsApp & Web)",
      tag: "Customer Support / FAQ",
      description: "AI support chatbot trained on your docs that answers FAQs 24/7 and drafts escalation tickets.",
      problem: "Support teams spend hours answering identical customer inquiries every day.",
      solution: "A custom LLM chatbot integrated into WhatsApp that answers questions instantly and qualifies leads.",
      features: ["24/7 instant AI responses", "WhatsApp Business sync", "Lead details collection", "Human escalation trigger"],
      accent: "#6366f1",
      icon: "bot",
    },
    {
      id: "ai-leads",
      title: "Sales Lead Router & WhatsApp Auto-responder",
      tag: "Sales / Lead Follow-up",
      description: "Instantly reads incoming leads from Google Sheets, sends custom WhatsApp messages, and alerts sales.",
      problem: "Sales conversions drop when lead response time is longer than 5 minutes.",
      solution: "An automated workflow that triggers the moment a form is filled, sending a personalized message instantly.",
      features: ["Google Sheets API triggers", "Personalized text templates", "Slack/Email sales alerts", "Lead tracking statuses"],
      accent: "#10b981",
      icon: "spark",
    },
    {
      id: "ai-ugc",
      title: "AI Video Creator & Social Scheduler",
      tag: "Marketing / Content Automation",
      description: "Generates video script ideas, synthesizes AI voiceovers, and schedules video files across platforms.",
      problem: "Creators struggle to post reels daily due to video editing and scripting delays.",
      solution: "A workflow that automatically generates voiceover audio, merges b-roll clips, and posts to reels.",
      features: ["Script outline generator", "AI voiceover generator sync", "Auto video compiling", "Social scheduling triggers"],
      accent: "#f59e0b",
      icon: "video",
    },
    {
      id: "ai-invoice",
      title: "E-invoice & PDF OCR Line Extractor",
      tag: "Finance / Operations",
      description: "Scans email PDF receipts, extracts pricing line items via OCR, and uploads directly to QuickBooks.",
      problem: "Accounting teams waste days typing line items from invoice PDFs manually.",
      solution: "An automated pipeline that reads PDFs via OCR, validates amounts, and syncs to accounting tools.",
      features: ["PDF document reader OCR", "Calculations double-checker", "Direct QuickBooks API sync", "Error logging alerts"],
      accent: "#3b82f6",
      icon: "file",
    },
  ],
  "logo-branding": [
    {
      id: "brand-minimal",
      title: "Minimalist Tech Brand Identity",
      tag: "Tech / Modern Startups",
      description: "Clean modern typography vectors, futuristic logo icon, and dark/light mode palette assets.",
      problem: "New startups look amateur without a structured, modern, vector-perfect brand system.",
      solution: "A high-end minimal identity bundle including dynamic font pairings, colors, and responsive vector SVGs.",
      features: ["Responsive vector SVG paths", "Font pairing stylesheet", "Light/Dark background guides", "Brand booklet template"],
      accent: "#6366f1",
      icon: "palette",
    },
    {
      id: "brand-retail",
      title: "Premium Lifestyle & Retail Identity",
      tag: "Lifestyle / E-Commerce",
      description: "Warm organic colors, elegant typography wordmark, and premium packaging label templates.",
      problem: "Product brands fail to justify premium pricing due to basic, generic logo designs.",
      solution: "An organic luxury branding system with elegant typography, custom packaging vectors, and brand guide.",
      features: ["Packaging label guidelines", "Warm editorial font sheets", "Custom vectors assets", "Social media templates"],
      accent: "#ec4899",
      icon: "briefcase",
    },
    {
      id: "brand-creator",
      title: "Bold Creator & Media Brand Kit",
      tag: "Media / Content Creators",
      description: "High-contrast geometric shapes, neon accent templates, and social media header banners.",
      problem: "Social media creators struggle to stay recognizable across different media channels.",
      solution: "A bold, cohesive brand kit with high-contrast layouts, custom stream templates, and avatar mockups.",
      features: ["Cohesive avatars templates", "High-contrast geometric styles", "Dynamic stream overlay assets", "Social banner templates"],
      accent: "#f59e0b",
      icon: "spark",
    },
    {
      id: "brand-corporate",
      title: "Corporate Trust Identity Bundle",
      tag: "Consulting / Finance",
      description: "Professional slate-blue colors, balanced symmetrical wordmark, and letterhead guides.",
      problem: "Financial/legal firms struggle to project corporate authority with modern amateur logos.",
      solution: "A symmetrical branding system prioritizing legibility, vector precision, and professional stationary guides.",
      features: ["Print-ready letterhead formats", "Corporate color guides", "Balanced symmetrical icon", "Presentation slide decks"],
      accent: "#3b82f6",
      icon: "shield",
    },
  ],
  "video-editing": [
    {
      id: "vid-viral",
      title: "Viral Tiktok & Instagram Reels Editing Flow",
      tag: "Social Media / TikTok",
      description: "High-energy zoom cuts, sound effects, colored kinetic text subtitles, and upbeat pacing.",
      problem: "Reels get scrolled past instantly without engaging hooks and fast-paced edits.",
      solution: "A viral editing system with synchronized sound effects, visual zoom callouts, and colored dynamic captions.",
      features: ["Kinetic text subtitle sync", "Visual zoom hooks", "Engagement sound design", "Fast pacing cuts"],
      accent: "#ec4899",
      icon: "video",
    },
    {
      id: "vid-doc",
      title: "Premium YouTube Documentary & Storytelling Style",
      tag: "YouTube / Documentary",
      description: "Smooth slide transitions, cinematic color grading, slow-motion overlays, and deep voiceover sync.",
      problem: "Long-form videos suffer from low watch-time without pacing variety and clean b-rolls.",
      solution: "A documentary-style edit featuring color grading, smooth slide overlays, and balanced sound mixing.",
      features: ["Cinematic color mapping", "Clean slide b-roll sync", "Deep sound/music mixing", "Long-form pacing structures"],
      accent: "#3b82f6",
      icon: "globe",
    },
    {
      id: "vid-ad",
      title: "Scroll-Stopping Facebook/Instagram Video Ads",
      tag: "E-Commerce Ads / UGC",
      description: "15-second product promo clips with bold text callouts, split-screen modes, and strong CTAs.",
      problem: "Ad budgets are wasted on generic videos that fail to explain product value in 3 seconds.",
      solution: "High-impact social ad videos prioritizing hook variations, split screens, and animated benefit callouts.",
      features: ["3-second hook variations", "Split-screen product showcase", "Bold value callout text", "Actionable call-to-actions"],
      accent: "#10b981",
      icon: "megaphone",
    },
    {
      id: "vid-explain",
      title: "Explainer Video & Vector Motion Graphics",
      tag: "SaaS / Product Explainer",
      description: "Animated flat vector shapes, product dashboard screen captures, and synced narration.",
      problem: "SaaS products struggle to onboard new users without visual step-by-step guides.",
      solution: "An animated explainer video using animated dashboard layouts and clear voiceover guidance.",
      features: ["Dashboard capture guides", "Animated flat vector shapes", "Synced narration tracks", "Onboarding step highlights"],
      accent: "#8b5cf6",
      icon: "file",
    },
  ],
  "digital-marketing": [
    {
      id: "mkt-maps",
      title: "Local Google Maps SEO Optimizer",
      tag: "Local SEO / GBP Boost",
      description: "Google Business Profile optimization, keyword citation building, and automatic review reminders.",
      problem: "Local shops lose nearby organic customers to competitors ranking higher on Google Maps.",
      solution: "A Maps SEO package to align keywords, build citations, and automate customer reviews generation.",
      features: ["Google Maps profile audits", "Local citation submissions", "Reviews reminder automation", "Location map embed code"],
      accent: "#3b82f6",
      icon: "globe",
    },
    {
      id: "mkt-ads",
      title: "High-ROAS Facebook & Meta Ads Campaign",
      tag: "Paid Advertising / Leads",
      description: "Custom audience research, split-test copies, pixel tracking, and lead-gen landing page setup.",
      problem: "E-commerce brands waste money on broad Meta ads without proper custom audience splits.",
      solution: "A results-oriented campaign setup featuring creative testing, custom exclusions, and pixel conversions.",
      features: ["Meta Pixel tracking setup", "Audience research blueprints", "Copy variations split tests", "Lead funnel design"],
      accent: "#ec4899",
      icon: "megaphone",
    },
    {
      id: "mkt-seo",
      title: "On-Page SEO & Content Marketing Blueprint",
      tag: "Organic Growth / SEO",
      description: "Full site technical audit, page speed enhancements, and keyword content outlines.",
      problem: "Websites receive zero organic search traffic due to slow load times and unoptimized keywords.",
      solution: "On-page content blueprint mapping key search terms, headings layout, and page speed adjustments.",
      features: ["Keyword maps sheets", "Technical SEO audits", "Speed performance edits", "Blog outline planners"],
      accent: "#10b981",
      icon: "chart",
    },
    {
      id: "mkt-funnel",
      title: "Automated WhatsApp & Email Marketing Funnel",
      tag: "Automation / Retention",
      description: "Automated sequence flows for abandoned carts, broadcast triggers, and lead capture boxes.",
      problem: "Online stores lose 70% of potential buyers who abandon carts and never receive follow-ups.",
      solution: "Automated follow-up drip campaigns on WhatsApp and Email reminding users to complete checkout.",
      features: ["Abandoned cart triggers", "Drip sequencers configurations", "Lead capture forms", "Discount coupon trigger"],
      accent: "#f59e0b",
      icon: "spark",
    },
  ],
};
